#!/bin/bash

set -e

CRLF=$(echo -e "\r\n")
HTTP_REQUEST="$(cat <<EOF
GET /index.html HTTP/1.1${CRLF}
Host: www.example.com${CRLF}
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) 
Gecko/20100101 Firefox/97.0${CRLF}
Accept: 
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/
webp,*/*;q=0.8${CRLF}
Accept-Language: en-US,en;q=0.5${CRLF}
Accept-Encoding: gzip, deflate, br${CRLF}
Connection: keep-alive${CRLF}
Referer: https://www.google.com/${CRLF}
Cache-Control: max-age=0${CRLF}
Upgrade-Insecure-Requests: 1${CRLF}
If-Modified-Since: Tue, 01 Feb 2022 12:00:00 GMT${CRLF}
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l${CRLF}
Cookie: session=abc123; user=JohnDoe${CRLF}
X-Requested-With: XMLHttpRequest${CRLF}
X-Forwarded-For: 192.168.1.1${CRLF}
${CRLF}
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
EOF
)"

echo "sending http request:"
echo "$HTTP_REQUEST"
nc -v localhost 8000 <<<$HTTP_REQUEST
